trigger:
- master
- releases/*

pool:
  name: Linux

resources:
  repositories:
    - repository: templates
      type: git
      ref: refs/heads/releases/0.2.0
      name: GTOKL-DevOps/azdo-pipeline-templates
      trigger: none

parameters:
  - name: enableVeracodeScan
    displayName: Enable Veracode Scan
    type: boolean
    default: true
  - name: veracodeFailBuildOnPolicyFail
    displayName: Abort on policy fail
    type: boolean
    default: true
